### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ruzko** [cego/nebula-provisioner#571]
Hope this issue finds you well,

I'm building an open source solution for privacy focused camera surveillance on farms, with integrated detection and deterring of predators. [Project repo here](https://gitlab.com/papiris/ml-predator-control-thesis)

I've provisioned a few nebula hosts manually, but the process isn't sustainable or scalable.
Went out looking for a nebula provisioning UI of sorts, which could automate the process of installing nebula on hosts and setting them up correctly.
Thus I came upon thine `nebula-provisioner` repo :)

Had a look in the source code and confirmed it pulls in `slackhq/nebula`, so I'm fairly certain it's in the ballpark of what I want to achieve. Although, figuring out exactly _how_ `nebula-provisioner` is supposed to be set up and used is difficult without documentation.

It would be super helpful if you could add:
- License  ([Open Source Definition](https://opensource.org/osd) compliant license is a must for me. [Capable of being included in (A)GPL-v3 licensed codebase ](https://www.gnu.org/licenses/quick-guide-gplv3.html#new-compatible-licenses) would be the greatest :1st_place_medal: )
- Readme  (Describing what `nebula-provisioner` does, and how to set it up :wrench: )

If you could add these, I could open pull requests for additional documentation as I discover features and limitations myself :memo: 

<br>

Best regards,
Jacob Ludvigsen

**Comment by SlyngDK** [comment]
Hi @ruzko 

Sounds like an interesting project.

Could you explain what you are looking, then I can answer if that, is a use case this project can support.
- What provision flow are you expecting?
- What are you expecting related to configuration of nebula.

## Short summary of the 3 components:
### server
- CA
- Webapp
- Backend for agents
- Embedded Encrypted DB
### server-client
Cli client for the server, for initial setup and some part which is not created in the webapp.
### agent
Running beside nebula, generating config and install cert, and afterwards reload nebula. 
Enrollment is initialized and changed by the agent, and approved in the provisioner if there are changes.
Designed to be deployed using ansible, including configuration, firewall rules and groups.

Best regards,
Simon
